# Generated by Django 3.1.2 on 2020-10-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Store', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('phone_no', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
    ]
